import { NextResponse } from "next/server";

const profileData = {
  id: "user-001",
  name: {
    first: "Musharof",
    last: "Chowdhury",
    full: "Musharof Chowdhury",
  },
  role: "Team Manager",
  location: "Arizona, United States",
  avatar: "/images/user/owner.jpg",
  bio: "Driving SquadGoo service excellence and mentoring the cross-border support team.",
  personalInfo: {
    email: "randomuser@pimjo.com",
    phone: "+09 363 398 46",
    address: "54 Crown Road, Phoenix",
    timezone: "UTC-7",
    city: "Phoenix",
    state: "Arizona",
    zip: "85001",
    country: "United States",
  },
  social: {
    facebook: "https://www.facebook.com/PimjoHQ",
    twitter: "https://x.com/PimjoHQ",
    linkedin: "https://www.linkedin.com/company/pimjo",
    instagram: "https://instagram.com/PimjoHQ",
  },
  reviews: [
    {
      id: "review-1",
      rating: 5,
      author: "Jasmine Patel",
      subject: "Priority escalation: cross-region SLA",
      serviceArea: "Global escalations",
      channel: "live chat",
      text: "Always responsive and resolves escalations patiently, even for cross-region teams.",
      date: "2025-12-08T13:20:00Z",
    },
    {
      id: "review-2",
      rating: 4,
      author: "Ravi Kumar",
      subject: "Premium workflow onboarding",
      serviceArea: "Finance ops",
      channel: "call",
      text: "Walked me through the premium workflow and synced the implementation notes with finance.",
      date: "2025-12-03T09:17:00Z",
    },
    {
      id: "review-3",
      rating: 5,
      author: "Sarah Ellis",
      subject: "High-priority courier case",
      serviceArea: "Logistics support",
      channel: "live chat",
      text: "Calm, professional, and able to coordinate high-priority cases without escalation.",
      date: "2025-11-29T16:56:00Z",
    },
    {
      id: "review-4",
      rating: 4,
      author: "Thomas Reed",
      subject: "Rush onboarding follow-up",
      serviceArea: "Onboarding",
      channel: "email",
      text: "Handled a rush onboarding and kept our internal stakeholders updated in real time.",
      date: "2025-11-22T11:10:00Z",
    },
    {
      id: "review-5",
      rating: 3,
      author: "Linda Park",
      subject: "Billing clarification request",
      serviceArea: "Accounting",
      channel: "call",
      text: "Resolved the chat ticket quickly but I needed a follow-up email to clarify the billing issue.",
      date: "2025-11-14T08:45:00Z",
    },
    {
      id: "review-6",
      rating: 5,
      author: "Alyssa Brown",
      subject: "Fraud prevention coordination",
      serviceArea: "Risk operations",
      channel: "live chat",
      text: "Coached the analyst team through an unusual payment hold and shared the specialist knowledge base.",
      date: "2025-11-10T14:00:00Z",
    },
    {
      id: "review-7",
      rating: 4,
      author: "Mateo Lopez",
      subject: "Contractor payout dispute",
      serviceArea: "Dispute desk",
      channel: "email",
      text: "Negotiated with the contractor and finance to restore the payout while keeping the customer informed.",
      date: "2025-11-05T10:30:00Z",
    },
  ],
  feedback: [
    {
      id: "feedback-1",
      type: "live chat",
      direction: "received",
      summary: "Allowed the customer to self-serve within 3 minutes and shared follow-ups.",
      timestamp: "2025-12-12T11:15:00Z",
      author: "Jasmine Patel",
      rating: 5,
      status: "reviewed",
    },
    {
      id: "feedback-2",
      type: "call",
      direction: "given",
      summary: "Escalated the pricing call to finance with clear documentation.",
      timestamp: "2025-12-10T09:40:00Z",
      author: "Ravi Kumar",
      rating: 4,
      status: "actioned",
    },
    {
      id: "feedback-3",
      type: "live chat",
      direction: "given",
      summary: "Closed the chat with a screenshot of the audit log for verification.",
      timestamp: "2025-12-07T16:04:00Z",
      author: "Sarah Ellis",
      rating: 5,
      status: "follow-up",
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Follow up on Customer 1024 ticket",
      description: "Verify documentation and update CRM notes.",
      dueDate: "2025-12-13",
      dueTime: "09:30",
      status: "completed",
      priority: "high",
      assignedBy: "Super Admin",
      isToday: true,
    },
    {
      id: "task-2",
      title: "Review dispute logs",
      description: "Summarize the logs for the morning stand-up.",
      dueDate: "2025-12-14",
      dueTime: "11:00",
      status: "pending",
      priority: "medium",
      assignedBy: "Super Admin",
      isToday: false,
    },
    {
      id: "task-3",
      title: "Call premium partner",
      description: "Confirm integrations and update CRM.",
      dueDate: "2025-12-13",
      dueTime: "14:15",
      status: "completed",
      priority: "low",
      assignedBy: "Super Admin",
      isToday: true,
    },
    {
      id: "task-5",
      title: "Escalation queue sweep",
      description: "Review high-priority escalations and assign owners.",
      dueDate: "2025-12-13",
      dueTime: "10:45",
      status: "assigned",
      priority: "high",
      assignedBy: "Super Admin",
      isToday: true,
    },
    {
      id: "task-6",
      title: "Daily SLA report",
      description: "Compile SLA breaches and share with leadership.",
      dueDate: "2025-12-13",
      dueTime: "12:30",
      status: "pending",
      priority: "medium",
      assignedBy: "Super Admin",
      isToday: true,
    },
    {
      id: "task-7",
      title: "Customer recovery follow-up",
      description: "Call back escalated customers from yesterday.",
      dueDate: "2025-12-13",
      dueTime: "15:20",
      status: "completed",
      priority: "high",
      assignedBy: "Super Admin",
      isToday: true,
    },
    {
      id: "task-8",
      title: "QA script refresh",
      description: "Update QA scripts for the new refund workflow.",
      dueDate: "2025-12-13",
      dueTime: "16:10",
      status: "assigned",
      priority: "low",
      assignedBy: "Super Admin",
      isToday: true,
    },
    {
      id: "task-9",
      title: "Partner SLA check-in",
      description: "Review partner SLA logs and note exceptions.",
      dueDate: "2025-12-13",
      dueTime: "17:30",
      status: "pending",
      priority: "medium",
      assignedBy: "Super Admin",
      isToday: true,
    },
    {
      id: "task-4",
      title: "Send survey follow-up",
      description: "Request rating from the last onboarding call.",
      dueDate: "2025-12-15",
      dueTime: "16:45",
      status: "assigned",
      priority: "medium",
      assignedBy: "Super Admin",
      isToday: false,
    },
  ],
};

export async function GET() {
  return NextResponse.json(profileData);
}
