import { NextRequest, NextResponse } from "next/server";
import type {
  StaffDashboardPayload,
  StaffRoleKey,
  StaffPriority,
} from "@/types/staff-dashboard";

const now = () => new Date();

const minutesAgo = (minutes: number) => {
  const date = now();
  date.setMinutes(date.getMinutes() - minutes);
  return date.toISOString();
};

const formatDateLabel = () =>
  now().toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
  });

const roleLabels: Record<StaffRoleKey, string> = {
  "customer-support": "Customer support",
  "recruiter-support": "Recruiter support",
  "dispute-desk": "Dispute resolution",
  manager: "Manager",
  "super-admin": "Super admin",
};

type RoleDash = Omit<
  StaffDashboardPayload,
  "updatedAt" | "role" | "roleLabel" | "dateLabel"
>;

const roleDashboards: Record<StaffRoleKey, RoleDash> = {
  "customer-support": {
    shift: "Morning shift - 9:00 AM - 5:00 PM",
    todayHeadline: "Triage transferred chats first, then same-day callbacks.",
    overview: [
      {
        id: "new-queries",
        label: "New queries assigned today",
        count: 7,
        href: "/support-tickets",
        priority: "medium",
        desc: "Fresh tickets that landed during your shift.",
      },
      {
        id: "unsolved-queries",
        label: "Unsolved / open queries",
        count: 18,
        href: "/support-tickets?filter=pending",
        priority: "high",
        desc: "Unresolved cases that need your reply.",
      },
      {
        id: "pending-live",
        label: "Pending live chats",
        count: 3,
        href: "/AdminChat?mode=live",
        priority: "high",
        desc: "Chats are waiting without a reply.",
      },
      {
        id: "transferred-to-you",
        label: "Tickets transferred to you",
        count: 2,
        href: "/AdminChat?mode=live",
        priority: "high",
        desc: "High-priority handovers to action now.",
      },
      {
        id: "followups",
        label: "Follow-ups due today",
        count: 4,
        href: "/MyTask",
        priority: "high",
        desc: "Reminders and callbacks scheduled for today.",
      },
      {
        id: "dept-unresolved",
        label: "Department unresolved",
        count: 32,
        href: "/CustomerService",
        priority: "medium",
        desc: "Backlog across Customer Ops.",
      },
    ],
    transfers: [
      {
        id: "trans-1",
        title: "Ticket #323538 - Unable to reset password",
        from: "Sana Iqbal (Manager)",
        transferredAt: minutesAgo(12 * 60),
        lastResponseMinutes: 90,
        href: "/AdminChat?ticket=323538&mode=live",
        type: "ticket",
        priority: "high",
        note: "Transferred 12 hours ago - no response yet.",
      },
      {
        id: "trans-2",
        title: "Chat - Courier route clarification",
        from: "Arman Lee (Support)",
        transferredAt: minutesAgo(45),
        lastResponseMinutes: 35,
        href: "/AdminChat?ticket=323537&mode=live",
        type: "chat",
        priority: "high",
        note: "Waiting 35 min; user is online.",
      },
    ],
    liveChats: {
      open: 2,
      pending: 3,
      transferred: 1,
      items: [
        {
          id: "chat-1",
          customer: "Umair Khan",
          status: "open",
          waitMinutes: 6,
          href: "/AdminChat?ticket=323538&mode=live",
          priority: "high",
          channel: "live-chat",
        },
        {
          id: "chat-2",
          customer: "Jasmine Patel",
          status: "pending",
          waitMinutes: 18,
          href: "/AdminChat?ticket=323537&mode=live",
          priority: "high",
          channel: "live-chat",
        },
        {
          id: "chat-3",
          customer: "Ravi Kumar",
          status: "transferred",
          waitMinutes: 28,
          href: "/AdminChat?ticket=323534&mode=live",
          priority: "medium",
          channel: "live-chat",
        },
      ],
    },
    departments: [
      {
        id: "dept-custops",
        name: "Customer Ops",
        newToday: 24,
        unresolved: 65,
        href: "/CustomerService",
        info: "Escalations from overnight still open.",
      },
    ],
    notifications: [
      {
        id: "notif-1",
        title: "New ticket assigned - #SUP-771",
        detail: "Reactivation request needs a callback within 2h.",
        timeAgo: "7m ago",
        href: "/support-tickets",
        priority: "high",
        type: "ticket",
      },
      {
        id: "notif-2",
        title: "Live chat transferred to you",
        detail: "LIST-5001 buyer follow-up needs verification screenshot.",
        timeAgo: "18m ago",
        href: "/AdminChat?ticket=323537&mode=live",
        priority: "high",
        type: "chat",
      },
      {
        id: "notif-3",
        title: "Follow-up reminder",
        detail: "Fraud check callback for Jobseeker 1024 due today.",
        timeAgo: "35m ago",
        href: "/MyTask",
        priority: "medium",
        type: "follow-up",
      },
      {
        id: "notif-4",
        title: "Conversation closed yesterday",
        detail: "Review outcome for courier case LIST-5010.",
        timeAgo: "12h ago",
        href: "/AdminChat?ticket=323534&mode=history",
        priority: "low",
        type: "history",
      },
    ],
    duties: [
      {
        id: "duty-1",
        label: "Jobseeker & recruiter profile review",
        detail: "Screen new documents for quick activation.",
        href: "/ApplicationsReview",
        priority: "medium",
      },
      {
        id: "duty-2",
        label: "Fraud checks",
        detail: "Flag mismatched IDs and SG coin reversals.",
        href: "/CustomerService",
        priority: "high",
      },
      {
        id: "duty-3",
        label: "Dispute resolution center",
        detail: "Assist mediators with customer statements.",
        href: "/DisputeResolution",
        priority: "medium",
      },
    ],
    followUps: [
      {
        id: "fu-1",
        title: "Call back - courier compensation",
        dueAt: minutesAgo(-90),
        context: "Customer requested proof of distance adjustment.",
        href: "/MyTask",
        priority: "high",
      },
      {
        id: "fu-2",
        title: "Review closed chat from yesterday",
        dueAt: minutesAgo(720),
        context: "Confirm resolution note for LIST-5010 buyer.",
        href: "/AdminChat?ticket=323534&mode=history",
        priority: "medium",
      },
    ],
    access: {
      menus: [
        "Support tickets",
        "Live chat",
        "My Task",
        "Notifications",
        "Customer Service",
      ],
      features: [
        "Ticket triage",
        "Live chat takeover",
        "Follow-up reminders",
        "Transfer visibility",
      ],
      departments: ["Customer Ops", "Frontline Support"],
    },
  },
  "recruiter-support": {
    shift: "Mid shift - 11:00 AM - 7:00 PM",
    todayHeadline: "Stabilize recruiter offers and nudge pending approvals.",
    overview: [
      {
        id: "new-queries",
        label: "New recruiter queries",
        count: 5,
        href: "/support-tickets",
        priority: "medium",
        desc: "Fresh recruiter-side tickets.",
      },
      {
        id: "pending-approvals",
        label: "Job approvals pending",
        count: 6,
        href: "/JobPostManagement",
        priority: "high",
        desc: "Jobs waiting for recruiter confirmation.",
      },
      {
        id: "followups",
        label: "Follow-ups due today",
        count: 3,
        href: "/MyTask",
        priority: "high",
        desc: "Recruiter callbacks you owe today.",
      },
      {
        id: "transfers",
        label: "Transferred recruiter tickets",
        count: 2,
        href: "/AdminChat?mode=live",
        priority: "high",
        desc: "Tickets routed to your queue.",
      },
      {
        id: "matching",
        label: "Matching engine reviews",
        count: 4,
        href: "/MatchingEngines",
        priority: "medium",
        desc: "Quick jobs needing human approval.",
      },
    ],
    transfers: [
      {
        id: "trans-3",
        title: "Ticket #REC-2201 - Offer refresh request",
        from: "Neha Kapoor (Manager)",
        transferredAt: minutesAgo(8 * 60),
        lastResponseMinutes: 140,
        href: "/AdminChat?ticket=REC-2201&mode=live",
        type: "ticket",
        priority: "high",
        note: "Recruiter is waiting for template reuse guidance.",
      },
      {
        id: "trans-4",
        title: "Chat - Dispute on job expiry",
        from: "Automated routing",
        transferredAt: minutesAgo(38),
        lastResponseMinutes: 22,
        href: "/AdminChat?ticket=REC-2204&mode=live",
        type: "chat",
        priority: "medium",
        note: "Escalated because job expired early.",
      },
    ],
    liveChats: {
      open: 1,
      pending: 2,
      transferred: 2,
      items: [
        {
          id: "chat-4",
          customer: "TalentMatch HR",
          status: "open",
          waitMinutes: 9,
          href: "/AdminChat?ticket=REC-2201&mode=live",
          priority: "high",
          channel: "live-chat",
        },
        {
          id: "chat-5",
          customer: "BrightHire Ops",
          status: "pending",
          waitMinutes: 24,
          href: "/AdminChat?ticket=REC-2204&mode=live",
          priority: "medium",
          channel: "live-chat",
        },
      ],
    },
    departments: [
      {
        id: "dept-recops",
        name: "Recruiter Success",
        newToday: 12,
        unresolved: 28,
        href: "/RecruiterDirectory",
        info: "Approvals and edits queued from last night.",
      },
    ],
    notifications: [
      {
        id: "notif-5",
        title: "New ticket assigned - Offer template",
        detail: "Help recruiter reuse last week's offer copy.",
        timeAgo: "15m ago",
        href: "/support-tickets",
        priority: "medium",
        type: "ticket",
      },
      {
        id: "notif-6",
        title: "Follow-up reminder",
        detail: "Call BrightHire about paused quick job.",
        timeAgo: "1h ago",
        href: "/MyTask",
        priority: "high",
        type: "follow-up",
      },
      {
        id: "notif-7",
        title: "Matching engine flagged 2 jobs",
        detail: "Manual review requested before pushing live.",
        timeAgo: "2h ago",
        href: "/MatchingEngines",
        priority: "medium",
        type: "job",
      },
    ],
    duties: [
      {
        id: "duty-4",
        label: "Recruiter onboarding",
        detail: "Verify KYB docs and set payment preferences.",
        href: "/RecruiterDirectory",
        priority: "medium",
      },
      {
        id: "duty-5",
        label: "Job activation checks",
        detail: "Approve edits that affect salary or duration.",
        href: "/JobPostManagement",
        priority: "high",
      },
      {
        id: "duty-6",
        label: "Callback commitments",
        detail: "Return recruiter callbacks before SLA.",
        href: "/MyTask",
        priority: "high",
      },
    ],
    followUps: [
      {
        id: "fu-3",
        title: "Review yesterday's closed chat",
        dueAt: minutesAgo(480),
        context: "Ensure recruiter received the final job link.",
        href: "/AdminChat?ticket=REC-2199&mode=history",
        priority: "medium",
      },
      {
        id: "fu-4",
        title: "Template approval note",
        dueAt: minutesAgo(-120),
        context: "Share approved wording for BrightHire renewal.",
        href: "/JobPostManagement",
        priority: "high",
      },
    ],
    access: {
      menus: [
        "Recruiter Directory",
        "Job Post Management",
        "My Task",
        "Matching Engines",
        "Notifications",
      ],
      features: [
        "Job approval",
        "Recruiter onboarding",
        "Template reuse",
        "Follow-up reminders",
      ],
      departments: ["Recruiter Success", "Job Health"],
    },
  },
  "dispute-desk": {
    shift: "Afternoon shift - 12:00 PM - 8:00 PM",
    todayHeadline: "Clear pending mediations and release holds with proof.",
    overview: [
      {
        id: "new-disputes",
        label: "New disputes today",
        count: 4,
        href: "/DisputeResolution",
        priority: "medium",
        desc: "New mediation cases opened this shift.",
      },
      {
        id: "open-holds",
        label: "SG coin holds pending",
        count: 5,
        href: "/DisputeResolution",
        priority: "high",
        desc: "Requires decision before auto-release.",
      },
      {
        id: "transfers",
        label: "Transferred disputes",
        count: 2,
        href: "/DisputeChat",
        priority: "high",
        desc: "Handovers needing immediate review.",
      },
      {
        id: "followups",
        label: "Follow-ups due today",
        count: 3,
        href: "/MyTask",
        priority: "high",
        desc: "Callbacks promised during mediation.",
      },
      {
        id: "live-chat",
        label: "Pending live chats",
        count: 2,
        href: "/DisputeChat",
        priority: "high",
        desc: "Customers waiting in dispute chat.",
      },
    ],
    transfers: [
      {
        id: "trans-5",
        title: "LIST-5001 - Marketplace hold > 7 days",
        from: "Auto-transfer",
        transferredAt: minutesAgo(14 * 60),
        lastResponseMinutes: 160,
        href: "/DisputeChat?case=LIST-5001",
        type: "dispute",
        priority: "high",
        note: "Transferred 14 hours ago - no response yet.",
      },
      {
        id: "trans-6",
        title: "JOB-8842 - Contractor payout dispute",
        from: "Sana Iqbal (Manager)",
        transferredAt: minutesAgo(62),
        lastResponseMinutes: 40,
        href: "/DisputeChat?case=JOB-8842",
        type: "dispute",
        priority: "high",
        note: "Waiting 40 min; contractor shared documents.",
      },
    ],
    liveChats: {
      open: 1,
      pending: 2,
      transferred: 1,
      items: [
        {
          id: "chat-6",
          customer: "Mia Collins",
          status: "open",
          waitMinutes: 5,
          href: "/DisputeChat?case=LIST-5001",
          priority: "high",
          channel: "live-chat",
        },
        {
          id: "chat-7",
          customer: "Omar Daniels",
          status: "pending",
          waitMinutes: 26,
          href: "/DisputeChat?case=LIST-7014",
          priority: "high",
          channel: "live-chat",
        },
      ],
    },
    departments: [
      {
        id: "dept-dispute",
        name: "Dispute Desk",
        newToday: 9,
        unresolved: 17,
        href: "/DisputeResolution",
        info: "Most holds are marketplace related.",
      },
    ],
    notifications: [
      {
        id: "notif-8",
        title: "Ticket transferred with no response",
        detail: "LIST-5001 needs mediator reply ASAP.",
        timeAgo: "12m ago",
        href: "/DisputeChat?case=LIST-5001",
        priority: "high",
        type: "dispute",
      },
      {
        id: "notif-9",
        title: "Follow-up reminder",
        detail: "Buyer confirmation call due by 6 PM.",
        timeAgo: "50m ago",
        href: "/MyTask",
        priority: "high",
        type: "follow-up",
      },
      {
        id: "notif-10",
        title: "Conversation closed yesterday",
        detail: "Review JOB-7721 settlement note.",
        timeAgo: "9h ago",
        href: "/DisputeChat?case=JOB-7721",
        priority: "medium",
        type: "history",
      },
    ],
    duties: [
      {
        id: "duty-7",
        label: "Settlement timers",
        detail: "Check cases nearing auto-release in 4h.",
        href: "/DisputeResolution",
        priority: "high",
      },
      {
        id: "duty-8",
        label: "Evidence review",
        detail: "Validate receipts and courier logs.",
        href: "/DisputeChat",
        priority: "high",
      },
      {
        id: "duty-9",
        label: "Wallet actions",
        detail: "Coordinate SG coin holds/releases.",
        href: "/AdminWallet",
        priority: "medium",
      },
    ],
    followUps: [
      {
        id: "fu-5",
        title: "Buyer callback on LIST-5001",
        dueAt: minutesAgo(-60),
        context: "Confirm delivery confirmation before release.",
        href: "/DisputeChat?case=LIST-5001",
        priority: "high",
      },
      {
        id: "fu-6",
        title: "Review closed mediation from yesterday",
        dueAt: minutesAgo(660),
        context: "Double-check settlement summary for JOB-7721.",
        href: "/DisputeChat?case=JOB-7721",
        priority: "medium",
      },
    ],
    access: {
      menus: [
        "Dispute Resolution",
        "Dispute Chat",
        "Admin Wallet",
        "My Task",
        "Notifications",
      ],
      features: [
        "Hold/release decisions",
        "Evidence collection",
        "Mediation chat",
        "Follow-up reminders",
      ],
      departments: ["Dispute Desk", "Risk & Wallet"],
    },
  },
  manager: {
    shift: "Manager on duty - 8:00 AM - 4:00 PM",
    todayHeadline: "Reassign workloads and clear high-priority handovers.",
    overview: [
      {
        id: "high-priority",
        label: "High-priority items",
        count: 6,
        href: "/Notifications",
        priority: "high",
        desc: "Critical handovers across teams.",
      },
      {
        id: "transfers",
        label: "Transferred conversations",
        count: 5,
        href: "/AdminChat?mode=live",
        priority: "high",
        desc: "Waiting more than 30 minutes.",
      },
      {
        id: "followups",
        label: "Follow-ups due today",
        count: 5,
        href: "/MyTask",
        priority: "high",
        desc: "Manager callbacks and approvals.",
      },
      {
        id: "open-disputes",
        label: "Disputes awaiting manager",
        count: 3,
        href: "/DisputeResolution",
        priority: "high",
        desc: "Requires approval before release.",
      },
      {
        id: "team-unresolved",
        label: "Team unresolved tickets",
        count: 38,
        href: "/support-tickets",
        priority: "medium",
        desc: "Backlog across support & dispute teams.",
      },
    ],
    transfers: [
      {
        id: "trans-7",
        title: "Live chat - Marketplace refund escalation",
        from: "Auto-transfer (breached 30m)",
        transferredAt: minutesAgo(70),
        lastResponseMinutes: 45,
        href: "/AdminChat?ticket=MK-3080&mode=live",
        type: "chat",
        priority: "high",
        note: "Breach alert - needs new owner.",
      },
      {
        id: "trans-8",
        title: "Dispute - LIST-7002 evidence request",
        from: "Dispute Desk",
        transferredAt: minutesAgo(6 * 60),
        lastResponseMinutes: 120,
        href: "/DisputeChat?case=LIST-7002",
        type: "dispute",
        priority: "high",
        note: "Waiting for manager decision.",
      },
    ],
    liveChats: {
      open: 2,
      pending: 3,
      transferred: 2,
      items: [
        {
          id: "chat-8",
          customer: "Sana Noor",
          status: "open",
          waitMinutes: 11,
          href: "/AdminChat?ticket=MK-3080&mode=live",
          priority: "high",
          channel: "live-chat",
        },
        {
          id: "chat-9",
          customer: "Omar Daniels",
          status: "pending",
          waitMinutes: 34,
          href: "/DisputeChat?case=LIST-7014",
          priority: "high",
          channel: "live-chat",
        },
      ],
    },
    departments: [
      {
        id: "dept-support",
        name: "Support",
        newToday: 19,
        unresolved: 41,
        href: "/support-tickets",
        info: "Long-tail tickets need reassignment.",
      },
      {
        id: "dept-disputes",
        name: "Disputes",
        newToday: 7,
        unresolved: 14,
        href: "/DisputeResolution",
        info: "Three cases require manager approval.",
      },
    ],
    notifications: [
      {
        id: "notif-11",
        title: "Escalation breached SLA",
        detail: "Marketplace refund chat waiting 45m.",
        timeAgo: "9m ago",
        href: "/AdminChat?ticket=MK-3080&mode=live",
        priority: "high",
        type: "chat",
      },
      {
        id: "notif-12",
        title: "Dispute approval needed",
        detail: "LIST-7002 requires hold decision.",
        timeAgo: "1h ago",
        href: "/DisputeChat?case=LIST-7002",
        priority: "high",
        type: "dispute",
      },
      {
        id: "notif-13",
        title: "Follow-up reminders",
        detail: "5 manager callbacks scheduled today.",
        timeAgo: "2h ago",
        href: "/MyTask",
        priority: "medium",
        type: "follow-up",
      },
    ],
    duties: [
      {
        id: "duty-10",
        label: "Shift assignments",
        detail: "Confirm coverage for live chat + dispute.",
        href: "/InternalChat",
        priority: "high",
      },
      {
        id: "duty-11",
        label: "Escalation routing",
        detail: "Reassign breached chats to active staff.",
        href: "/AdminChat?mode=live",
        priority: "high",
      },
      {
        id: "duty-12",
        label: "Quality reviews",
        detail: "Spot check yesterday's closures.",
        href: "/Notifications",
        priority: "medium",
      },
    ],
    followUps: [
      {
        id: "fu-7",
        title: "Review closed conversation from yesterday",
        dueAt: minutesAgo(540),
        context: "Ticket #SUP-771 auto-closed; verify outcome.",
        href: "/support-tickets",
        priority: "medium",
      },
      {
        id: "fu-8",
        title: "Manager callback set",
        dueAt: minutesAgo(-150),
        context: "Call recruiter about paused job approval.",
        href: "/JobPostManagement",
        priority: "high",
      },
    ],
    access: {
      menus: [
        "Live chat",
        "Support tickets",
        "Dispute Resolution",
        "Notifications",
        "My Task",
      ],
      features: [
        "Reassign workloads",
        "Approve disputes",
        "Quality review",
        "Callback commitments",
      ],
      departments: ["Support", "Disputes", "Recruiter Ops"],
    },
  },
  "super-admin": {
    shift: "Super admin - Flexible",
    todayHeadline: "Monitor platform health; use Super Admin Dashboard for KPIs.",
    overview: [
      {
        id: "platform-alerts",
        label: "Platform alerts",
        count: 3,
        href: "/Notifications",
        priority: "high",
        desc: "High-severity operational alerts.",
      },
      {
        id: "staff-handovers",
        label: "Staff handovers",
        count: 4,
        href: "/InternalChat",
        priority: "medium",
        desc: "Pending approvals or access changes.",
      },
      {
        id: "open-disputes",
        label: "Disputes awaiting decision",
        count: 2,
        href: "/DisputeResolution",
        priority: "high",
        desc: "Approval needed before release.",
      },
      {
        id: "super-admin-dashboard",
        label: "Super admin dashboard",
        count: 1,
        href: "/super-admin-dashboard",
        priority: "medium",
        desc: "Access platform KPIs and trends.",
      },
    ],
    transfers: [
      {
        id: "trans-9",
        title: "High-risk wallet case",
        from: "Risk Automation",
        transferredAt: minutesAgo(180),
        lastResponseMinutes: 80,
        href: "/AdminWallet",
        type: "dispute",
        priority: "high",
        note: "Needs super admin review for release.",
      },
    ],
    liveChats: {
      open: 0,
      pending: 1,
      transferred: 0,
      items: [
        {
          id: "chat-10",
          customer: "Platform alert",
          status: "pending",
          waitMinutes: 15,
          href: "/InternalChat",
          priority: "medium",
          channel: "live-chat",
        },
      ],
    },
    departments: [
      {
        id: "dept-platform",
        name: "Platform Controls",
        newToday: 2,
        unresolved: 5,
        href: "/PlatformControls",
        info: "Feature toggles pending approval.",
      },
    ],
    notifications: [
      {
        id: "notif-14",
        title: "ATO export ready",
        detail: "GST pack available for review.",
        timeAgo: "30m ago",
        href: "/ATOReports",
        priority: "medium",
        type: "report",
      },
      {
        id: "notif-15",
        title: "Platform toggle requested",
        detail: "Marketplace toggle change pending.",
        timeAgo: "1h ago",
        href: "/PlatformControls",
        priority: "medium",
        type: "control",
      },
    ],
    duties: [
      {
        id: "duty-13",
        label: "Role visibility audit",
        detail: "Confirm menu visibility by role.",
        href: "/AdminPanelControl",
        priority: "medium",
      },
      {
        id: "duty-14",
        label: "Monitor KPIs",
        detail: "Use super admin dashboard for trends.",
        href: "/super-admin-dashboard",
        priority: "medium",
      },
    ],
    followUps: [
      {
        id: "fu-9",
        title: "Confirm platform toggle",
        dueAt: minutesAgo(-180),
        context: "Approve marketplace search rollout.",
        href: "/PlatformControls",
        priority: "high",
      },
    ],
    access: {
      menus: [
        "Super Admin Dashboard",
        "Admin Panel Control",
        "Platform Controls",
        "ATO Reports",
        "Notifications",
      ],
      features: [
        "Feature toggles",
        "Role visibility",
        "Exports",
        "Escalation oversight",
      ],
      departments: ["All departments"],
    },
  },
};

const ensureRole = (value: string | null): StaffRoleKey => {
  if (!value) {
    return "customer-support";
  }
  const lower = value.toLowerCase() as StaffRoleKey;
  if (lower in roleDashboards) {
    return lower;
  }
  return "customer-support";
};

const buildPayload = (role: StaffRoleKey): StaffDashboardPayload => {
  const base = roleDashboards[role] ?? roleDashboards["customer-support"];
  return {
    ...base,
    role,
    roleLabel: roleLabels[role],
    updatedAt: now().toISOString(),
    dateLabel: formatDateLabel(),
  };
};

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const requestedRole = ensureRole(searchParams.get("role"));
  const payload = buildPayload(requestedRole);

  return NextResponse.json(payload);
}
